/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/oversizedf.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/oversizedf.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_0004.geometry} material={materials.WOI} position={[0, 4.899, 0]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.062} />
    </group>
  )
}

useGLTF.preload('/oversizedf.glb')
